---
title: "TE_computation"
date: "Last update: Dec 2nd 2020"
output: html_document
---

# Preparations
## load libraries
```{r setup, include=FALSE}

library(here)
library(tidyverse)
library(tidylog)
library(ggpubr)
#library(regclass) # for correlation
#library(effects)
# library(jtools)
#library(FRACTION) # this allows us to use the is.wholenumber function

`%notin%` <- Negate(`%in%`)

```

# Simulation 1
## Infants of the same developmental level with different word vocabularies and balances of exposure
### V = 600
```{r}
# Generating the parameters
V <- 600 # setting V = 600 for the Simulation (keep V constant)

W <- seq(0, 2*V, by = 25) # a range of total word vocabulary of a child

B <- seq(0.5, 1, by = 0.1) # a range of Balance, i.e. proportion use of dominant language (B ≤ .50)

# Generating sequence of W and B
W_seq <- W %>% # a sequence of 0 to 2V
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>%  # a sequence of 0.5 to 1
  rep(., length(W)) # generate N repetitions of the sequence based on length of W

# Creating the dataframe
data_Simulation1 <- data.frame(V, W_seq) %>%
  arrange(W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B_seq) %>%
  # Create other variables
  mutate(D = B*W, # Words produced in the dominant language
         N = (1-B)*W, # Words produced in non-dominant language
         TE = (D*N)/V) %>% # If D and N are independent, TE = DN/V
  # It is also not possible for D or N to exceed V, so filter out cases where D or N > V
  filter_at(vars(D, N), all_vars(. <= V)) %>%
  # Round to keep whole numbers only
  mutate_at(vars(-B), round, 0)


# Visualizing Simulation 1
Simulation1 <- data_Simulation1 %>%
  # Convert to long data
  pivot_longer(c(W, D, N), names_to = "vocab_type", values_to = "number") %>%
  mutate(vocab_type = factor(vocab_type, levels=c("W", "D", "N"))) %>%
  mutate(vocab_type = recode(vocab_type, 
                             W = "Panel A: Total vocabulary (W)", 
                             D = "Panel B: Dominant vocabulary (D)", 
                             N = "Panel C: Non-dominant vocabulary (N)")) %>%
  mutate(B = as.factor(B)) %>%
  ggplot(aes(x = number, y = TE, color = B)) +
  #geom_point() +
  stat_smooth(method = lm, se = F) +
  theme_minimal() + 
  facet_grid(. ~ vocab_type) +
  ylim(0, 600) +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "bottom",
        plot.title = element_text(hjust = 0.5),
        text = element_text(size=12)) +
  labs(x = "Number of words", 
       y = "Total number of translation equivalents (TE)", 
       color = "Balance (B)"
       #, title = "Number of translation equivalent by balance in relation to different input measures "
       ) +
  guides(colour = guide_legend(nrow = 1))

ggsave("plot_Simulation1.png", Simulation1,
       width = 10, height = 5)

```


# Simulation 2
## Patterns of translation equivalent learning as a function of different developmental timepoints
### V = 150, 300, 450, or 600
```{r}
# V = 600
## Generating the parameters
V <- 600
W <- V # holding W constant
B <- seq(0.5, 1, by = 0.01) # a range of Balance, i.e. proportion use of dominant language (B ≤ .50)

## Generating sequence of W and B
W_seq <- W %>% 
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

## Creating the dataframe
TE_V600 <- data.frame(V, W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B)

# V = 450
## Generating the parameters
V <- 450
W <- V # holding W constant
B <- seq(0.5, 1, by = 0.01) # a range of Balance, i.e. proportion use of dominant language (B ≤ .50)

## Generating sequence of W and B
W_seq <- W %>% 
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

## Creating the dataframe
TE_V450 <- data.frame(V, W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B)

# V = 300
## Generating the parameters
V <- 300
W <- V # holding W constant
B <- seq(0.5, 1, by = 0.01) # a range of Balance, i.e. proportion use of dominant language (B ≤ .50)

## Generating sequence of W and B
W_seq <- W %>% 
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

## Creating the dataframe
TE_V300 <- data.frame(V, W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B)

# V = 150
## Generating the parameters
V <- 150
W <- V # holding W constant
B <- seq(0.5, 1, by = 0.01) # a range of Balance, i.e. proportion use of dominant language (B ≤ .50)

## Generating sequence of W and B
W_seq <- W %>% 
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

## Creating the dataframe
TE_V150 <- data.frame(V, W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B)


# Combining all the dataframes
data_Simulation2 <- rbind(TE_V150, TE_V300, TE_V450, TE_V600) %>%
  # Create other variables
  mutate(D = B*W, # Words produced in the dominant language
         N = (1-B)*W, # Words produced in non-dominant language
         TE = (D*N)/V, # If D and N are independent, TE = DN/V
         DU = D-TE, # Unique words in dominant language
         NU = N-TE) %>% # Unique words in non-dominant language
  # Round to keep whole numbers only
  mutate_at(vars(-B), round, 0)


# Visualizing Simulation 2
Simulation2 <- data_Simulation2 %>%
  mutate(bin_B = case_when(B < 0.6 ~ "0.5",
                           B >= 0.6 & B < 0.7 ~ "0.6",
                           B >= 0.7 & B < 0.8 ~ "0.7",
                           B >= 0.8 & B < 0.9 ~ "0.8",
                           TRUE ~ "0.9")) %>%
  pivot_longer(-c(V, W, B, bin_B), names_to = "vocab_type", values_to = "number") %>%
  filter(vocab_type %notin% c("D", "N")) %>%
  mutate(vocab_type = factor(vocab_type, levels=c("NU", "DU", "TE"))) %>%
  group_by(V, bin_B, vocab_type) %>%
  summarise(n_words = mean(number)) %>%
  ggplot(aes(x = bin_B, y = n_words, fill = vocab_type)) + 
  geom_bar(position="stack", stat="identity") +
  facet_grid(. ~ V) +
  scale_fill_manual(values = c("#1f78b4", "#a6cee3", "#33a02c")) + 
  #scale_y_continuous(limits = c(0, 1200)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90), 
        legend.position = "bottom",
        plot.title = element_text(hjust = 0.5),
        text = element_text(size=12)) + 
  labs(x = "Balance", 
       y = "Number of concepts", 
       title = "Vocabulary composition across different developmental timepoints (V)") 

ggsave("plot_Simulation2.png", Simulation2,
        width = 10, height = 5)

```


# Simulation 3
## Non-independence of dominant-language (D) and non-dominant language words (N)
```{r}
# V = 600
## Generating the parameters
V <- 600
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

## Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

## Creating the dataframe
TE_V600 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 

# V = 450
## Generating the parameters
V <- 450
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

## Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

## Creating the dataframe
TE_V450 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 

# V = 300
## Generating the parameters
V <- 300
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

## Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

## Creating the dataframe
TE_V300 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 

# V = 150
## Generating the parameters
V <- 150
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

## Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

## Creating the dataframe
TE_V150 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 


# Combining all the dataframes
data_Simulation3 <- rbind(TE_V150, TE_V300, TE_V450, TE_V600) %>%
  # It is not possible for N > D, so keep only cases where D >= N
  filter(D >= N) %>%
  # Create TE 
  mutate(W = D+N, # Total word vocabulary of a child
         B = D/(D+N), # Balance, i.e. proportion use of non-dominant language (B ≤ .50)
         TE = D*N/V) %>% # If D and N are independent, TE = DN/V
  # Remove cases where B = NaN (those were all cases where both D and N are 0)
  filter(!is.na(B)) %>%
  # Round to keep whole numbers only
  mutate_at(vars(-B), round, 0)


# Simulation3: TE = I * (D*N/V)
## Defining the independence parameter I
I1 = 1.5 # I > 1, TEs are MORE easily learned than unique words
I2 = 0.5 # I < 1, TEs are LESS easily learned than unique words

## Visualizing the simulation
Simulation3 <- data_Simulation3 %>%
  ## Calculate where I > 1
  mutate(TE_easier = I1*(D*N/V)) %>%
  ## Calculate where I < 1
  mutate(TE_harder = I2*(D*N/V)) %>%
  # Round to keep whole numbers only
  mutate_at(vars(-B), round, 0) %>%
  # Prepare dataset to plot
  pivot_longer(c(TE, TE_harder, TE_easier), 
               names_to = "Model", values_to = "number_TE") %>%
  mutate(Model = factor(Model, levels=c("TE_harder", "TE", "TE_easier"))) %>%
  mutate(Model = recode(Model, 
                        TE = "I = 1 (assuming independence of D and N)",
                        TE_easier = "I = 1.5 (TEs are more easily learned)",
                        TE_harder = "I = 0.5 (TE are less easily learned)")) %>%
  mutate(bin_B = cut(B, breaks = 6, 
                     labels = c("0.5", "0.6", "0.7", "0.8", "0.9", "1"))) %>%
  # ggplot
  ggplot(aes(x = W, y = number_TE, color = bin_B)) +
  stat_smooth(method = lm, se = F) +
  theme_minimal() + 
  facet_grid(. ~ Model) +
  ylim(0, 600) +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "bottom") +
  theme(plot.title = element_text(hjust = 0.5),
        text = element_text(size=12)) +
  labs(x = "Total word vocabulary (W)", 
       y = "Total number of translation equivalents (TE)", 
       color = "Balance (B)") +
  guides(colour = guide_legend(nrow = 1))

ggsave("plot_Simulation3.png", Simulation3, 
       width = 10, height = 5)

```