---
title: "TE_computation"
date: "Last update: Dec 2nd 2020"
output: html_document
---

# Preparations
## load libraries
```{r setup, include=FALSE}

library(here)
library(tidyverse)
library(tidylog)
library(ggpubr)
library(regclass) # for correlation
library(effects)
# library(jtools)
#library(FRACTION) # this allows us to use the is.wholenumber function

`%notin%` <- Negate(`%in%`)

```

# Generating dataframe for computational model
#### Set 1: Calculate other variables based on V, W, and B ####
```{r}
### Generating variables: V, W, and B
## V = 600 ##
# Items on vocabulary measure (e.g. words on the CDI)
V <- 600

# Total word vocabulary of a child
W <- seq(0, 2*V, by = 25) 

# Balance, i.e. proportion use of non-dominant language (B ≤ .50)
B <- seq(0.5, 1, by = 0.025) 

# Generating sequence of W and B
W_seq <- W %>% # a sequence of 0 to 2V
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>%  # a sequence of 0.5 to 1
  rep(., length(W)) # generate N repetitions of the sequence based on length of W

# Creating the dataframe
TE_V600 <- data.frame(V, W_seq) %>%
  arrange(W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B_seq)


## V = 550 ##
# Items on vocabulary measure (e.g. words on the CDI)
V <- 550

# Total word vocabulary of a child
W <- seq(0, 2*V, by = 25) 

# Balance, i.e. proportion use of non-dominant language (B ≤ .50)
B <- seq(0.5, 1, by = 0.025) 

# Generating sequence of W and B
W_seq <- W %>% # a sequence of 0 to 2V
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>%  # a sequence of 0.5 to 1
  rep(., length(W)) # generate N repetitions of the sequence based on length of W

# Creating the dataframe
TE_V550 <- data.frame(V, W_seq) %>%
  arrange(W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B_seq)


## V = 500 ##
# Items on vocabulary measure (e.g. words on the CDI)
V <- 500

# Total word vocabulary of a child
W <- seq(0, 2*V, by = 25) 

# Balance, i.e. proportion use of non-dominant language (B ≤ .50)
B <- seq(0.5, 1, by = 0.025) 

# Generating sequence of W and B
W_seq <- W %>% # a sequence of 0 to 2V
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>%  # a sequence of 0.5 to 1
  rep(., length(W)) # generate N repetitions of the sequence based on length of W

# Creating the dataframe
TE_V500 <- data.frame(V, W_seq) %>%
  arrange(W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B_seq)

  
## V = 450 ##
# Items on vocabulary measure (e.g. words on the CDI)
V <- 450

# Total word vocabulary of a child
W <- seq(0, 2*V, by = 25) 

# Balance, i.e. proportion use of non-dominant language (B ≤ .50)
B <- seq(0.5, 1, by = 0.025) 

# Generating sequence of W and B
W_seq <- W %>% # a sequence of 0 to 2V
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>%  # a sequence of 0.5 to 1
  rep(., length(W)) # generate N repetitions of the sequence based on length of W

# Creating the dataframe
TE_V450 <- data.frame(V, W_seq) %>%
  arrange(W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B_seq) 


## V = 400 ##
# Items on vocabulary measure (e.g. words on the CDI)
V <- 400

# Total word vocabulary of a child
W <- seq(0, 2*V, by = 25) 

# Balance, i.e. proportion use of non-dominant language (B ≤ .50)
B <- seq(0.5, 1, by = 0.025) 

# Generating sequence of W and B
W_seq <- W %>% # a sequence of 0 to 2V
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>%  # a sequence of 0.5 to 1
  rep(., length(W)) # generate N repetitions of the sequence based on length of W

# Creating the dataframe
TE_V400 <- data.frame(V, W_seq) %>%
  arrange(W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B_seq) 


## V = 350 ##
# Items on vocabulary measure (e.g. words on the CDI)
V <- 350

# Total word vocabulary of a child
W <- seq(0, 2*V, by = 25) 

# Balance, i.e. proportion use of non-dominant language (B ≤ .50)
B <- seq(0.5, 1, by = 0.025) 

# Generating sequence of W and B
W_seq <- W %>% # a sequence of 0 to 2V
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>%  # a sequence of 0.5 to 1
  rep(., length(W)) # generate N repetitions of the sequence based on length of W

# Creating the dataframe
TE_V350 <- data.frame(V, W_seq) %>%
  arrange(W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B_seq) 


## V = 300 ##
# Items on vocabulary measure (e.g. words on the CDI)
V <- 300

# Total word vocabulary of a child
W <- seq(0, 2*V, by = 25) 

# Balance, i.e. proportion use of non-dominant language (B ≤ .50)
B <- seq(0.5, 1, by = 0.025) 

# Generating sequence of W and B
W_seq <- W %>% # a sequence of 0 to 2V
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>%  # a sequence of 0.5 to 1
  rep(., length(W)) # generate N repetitions of the sequence based on length of W

# Creating the dataframe
TE_V300 <- data.frame(V, W_seq) %>%
  arrange(W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B_seq) 


## V = 250 ##
# Items on vocabulary measure (e.g. words on the CDI)
V <- 250

# Total word vocabulary of a child
W <- seq(0, 2*V, by = 25) 

# Balance, i.e. proportion use of non-dominant language (B ≤ .50)
B <- seq(0.5, 1, by = 0.025) 

# Generating sequence of W and B
W_seq <- W %>% # a sequence of 0 to 2V
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>%  # a sequence of 0.5 to 1
  rep(., length(W)) # generate N repetitions of the sequence based on length of W

# Creating the dataframe
TE_V250 <- data.frame(V, W_seq) %>%
  arrange(W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B_seq) 
 


## V = 200 ##
# Items on vocabulary measure (e.g. words on the CDI)
V <- 200

# Total word vocabulary of a child
W <- seq(0, 2*V, by = 25) 

# Balance, i.e. proportion use of non-dominant language (B ≤ .50)
B <- seq(0.5, 1, by = 0.025) 

# Generating sequence of W and B
W_seq <- W %>% # a sequence of 0 to 2V
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>%  # a sequence of 0.5 to 1
  rep(., length(W)) # generate N repetitions of the sequence based on length of W

# Creating the dataframe
TE_V200 <- data.frame(V, W_seq) %>%
  arrange(W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B_seq) 

 
## V = 150 ##
# Items on vocabulary measure (e.g. words on the CDI)
V <- 150

# Total word vocabulary of a child
W <- seq(0, 2*V, by = 25) 

# Balance, i.e. proportion use of non-dominant language (B ≤ .50)
B <- seq(0.5, 1, by = 0.025) 

# Generating sequence of W and B
W_seq <- W %>% # a sequence of 0 to 2V
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>%  # a sequence of 0.5 to 1
  rep(., length(W)) # generate N repetitions of the sequence based on length of W

# Creating the dataframe
TE_V150 <- data.frame(V, W_seq) %>%
  arrange(W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B_seq) 


## V = 100 ##
# Items on vocabulary measure (e.g. words on the CDI)
V <- 100

# Total word vocabulary of a child
W <- seq(0, 2*V, by = 25) 

# Balance, i.e. proportion use of non-dominant language (B ≤ .50)
B <- seq(0.5, 1, by = 0.025) 

# Generating sequence of W and B
W_seq <- W %>% # a sequence of 0 to 2V
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>%  # a sequence of 0.5 to 1
  rep(., length(W)) # generate N repetitions of the sequence based on length of W

# Creating the dataframe
TE_V100 <- data.frame(V, W_seq) %>%
  arrange(W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B_seq) 


## V = 50 ##
# Items on vocabulary measure (e.g. words on the CDI)
V <- 50

# Total word vocabulary of a child
W <- seq(0, 2*V, by = 25) 

# Balance, i.e. proportion use of non-dominant language (B ≤ .50)
B <- seq(0.5, 1, by = 0.025) 

# Generating sequence of W and B
W_seq <- W %>% # a sequence of 0 to 2V
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>%  # a sequence of 0.5 to 1
  rep(., length(W)) # generate N repetitions of the sequence based on length of W

# Creating the dataframe
TE_V50 <- data.frame(V, W_seq) %>%
  arrange(W_seq) %>%
  rename(W = W_seq) %>%
  mutate(B = B_seq) 


### Combining all dataframes and Calculate other variables
TE_fromVWB <- TE_fromVWB <- rbind(TE_V50, TE_V100, TE_V150, TE_V200, TE_V250, TE_V300, 
                                  TE_V350, TE_V400, TE_V450, TE_V500, TE_V550, TE_V600) %>%
  # Create other variables
  mutate(D = B*W, # Words produced in the dominant language
         N = (1-B)*W, # Words produced in non-dominant language
         TE = (D*N)/V, # If D and N are independent, TE = DN/V
         C = W-TE, # Concept vocabulary (or total conceptual vocabulary size)
         Du = D-TE, # Unique words in dominant language
         Nu = N-TE) %>% # Unique words in non-dominant language
  # In reality, it would be impossible to get negative numbers for any vocabulary variables, so filter out all cases with negative numbers
  filter(Nu >= 0) %>%
  # It is also not possible for D or N to exceed V, so filter out cases where D or N > V
  filter_at(vars(D, N), all_vars(. <= V)) %>%
  # Round to keep whole numbers only
  mutate_at(vars(-B), round, 0)

  ## filter out cases where D or N aren't whole numbers
  #filter_at(vars(D, N), any_vars(is.wholenumber(.))) 
```

#### Set 2: Calculate other variables based on V, D, and N ####
```{r}
### Generating variables: D and N
## V = 600 ##
V <- 600
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

# Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V600 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 


## V = 550 ##
V <- 550
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

# Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V550 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 


## V = 500 ##
V <- 500
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

# Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V500 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 


## V = 450 ##
V <- 450
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

# Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V450 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 


## V = 400 ##
V <- 400
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

# Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V400 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 


## V = 350 ##
V <- 350
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

# Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V350 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 


## V = 300 ##
V <- 300
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

# Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V300 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 


## V = 250 ##
V <- 250
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

# Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V250 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 


## V = 200 ##
V <- 200
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

# Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V200 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 


## V = 150 ##
V <- 150
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

# Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V150 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 


## V = 100 ##
V <- 100
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

# Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V100 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 


## V = 50 ##
V <- 50
D <- seq(0, V, by = 25) 
N <- seq(0, V, by = 25)

# Generating sequence of D and N
D_seq <- D %>% # Words produced in the dominant language
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

N_seq <- N %>% # Words produced in non-dominant language
  rep(., length(D)) # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V50 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(N = N_seq) 


### Combining all dataframes and Calculate other variables
TE_fromVDN <- rbind(TE_V50, TE_V100, TE_V150, TE_V200, TE_V250, TE_V300, 
                    TE_V350, TE_V400, TE_V450, TE_V500, TE_V550, TE_V600) %>%
  # It is not possible for N > D, so keep only cases where D >= N
  filter(D >= N) %>%
  # Create other variables
  mutate(W = D+N, # Total word vocabulary of a child
         B = D/(D+N), # Balance, i.e. proportion use of non-dominant language (B ≤ .50)
         TE = (D*N)/V, # If D and N are independent, TE = DN/V
         C = W-TE, # Concept vocabulary (or total conceptual vocabulary size)
         Du = D-TE, # Unique words in dominant language
         Nu = N-TE) %>%
  # Remove cases where B = NA
  filter(!is.na(B)) %>%
  # Round to keep whole numbers only
  mutate_at(vars(-B), round, 0)
```

#### Set 3: Calculate other variables based on V, D, and B ####
```{r}
### Creating variables: D and B
## V = 600 #
V <- 600
D <- seq(0, V, by = 25) 

D_seq <- D %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # balance
  rep(., length(D))  # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V600 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(B = B_seq) 


## V = 550 #
V <- 550
D <- seq(0, V, by = 25) 

D_seq <- D %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # balance
  rep(., length(D))  # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V550 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(B = B_seq) 


## V = 500 #
V <- 500
D <- seq(0, V, by = 25) 

D_seq <- D %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # balance
  rep(., length(D))  # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V500 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(B = B_seq) 


## V = 450 #
V <- 450
D <- seq(0, V, by = 25) 

D_seq <- D %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # balance
  rep(., length(D))  # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V450 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(B = B_seq) 


## V = 400 #
V <- 400
D <- seq(0, V, by = 25) 

D_seq <- D %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # balance
  rep(., length(D))  # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V400 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(B = B_seq) 


## V = 350 #
V <- 350
D <- seq(0, V, by = 25) 

D_seq <- D %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # balance
  rep(., length(D))  # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V350 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(B = B_seq) 


## V = 300 #
V <- 300
D <- seq(0, V, by = 25) 

D_seq <- D %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # balance
  rep(., length(D))  # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V300 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(B = B_seq) 


## V = 250 #
V <- 250
D <- seq(0, V, by = 25) 

D_seq <- D %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # balance
  rep(., length(D))  # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V250 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(B = B_seq) 


## V = 200 #
V <- 200
D <- seq(0, V, by = 25) 

D_seq <- D %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # balance
  rep(., length(D))  # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V200 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(B = B_seq) 


## V = 150 #
V <- 150
D <- seq(0, V, by = 25) 

D_seq <- D %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # balance
  rep(., length(D))  # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V150 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(B = B_seq) 


## V = 100 #
V <- 100
D <- seq(0, V, by = 25) 

D_seq <- D %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # balance
  rep(., length(D))  # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V100 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(B = B_seq) 


## V = 50 #
V <- 50
D <- seq(0, V, by = 25) 

D_seq <- D %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # balance
  rep(., length(D))  # generate N repetitions of the sequence based on length of D

# Creating the dataframe
TE_V50 <- data.frame(V, D_seq) %>%
  arrange(D_seq) %>%
  rename(D = D_seq) %>%
  mutate(B = B_seq) 

### Combining all dataframes and Calculate other variables
TE_fromVDB <- rbind(TE_V50, TE_V100, TE_V150, TE_V200, TE_V250, TE_V300, 
                    TE_V350, TE_V400, TE_V450, TE_V500, TE_V550, TE_V600) %>%
  # Create other variables
  mutate(W = D/B, # Total word vocabulary of a child
         N = W-D, # Words produced in non-dominant language
         TE = (D*N)/V, # If D and N are independent, TE = DN/V
         C = W-TE, # Concept vocabulary (or total conceptual vocabulary size)
         Du = D-TE, # Unique words in dominant language
         Nu = N-TE) %>% # Unique words in non-dominant language
  # In reality, it would be impossible to get negative numbers for any vocabulary variables, so filter out all cases with negative numbers
  filter(Nu >= 0) %>%
  # It is also not possible for D or N to exceed V, so filter out cases where D or N > V
  filter_at(vars(D, N), all_vars(. <= V)) %>%
  # Round to keep whole numbers only
  mutate_at(vars(-B), round, 0)
  
  ## filter out cases where N isn't whole number
  #filter(is.wholenumber(N))
```

#### Set 4: Calculate other variables based on V, N, and B ####
```{r}
### Generating variables: N and B
## V = 600 #
V <- 600
N <- seq(0, V, by = 25)

N_seq <- N %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # a sequence of 0.5 to 1
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

# Creating the dataframe
TE_V600 <- data.frame(V, N_seq) %>%
  arrange(N_seq) %>%
  rename(N = N_seq) %>%
  mutate(B = B_seq) 


## V = 550 #
V <- 550
N <- seq(0, V, by = 25)

N_seq <- N %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # a sequence of 0.5 to 1
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

# Creating the dataframe
TE_V550 <- data.frame(V, N_seq) %>%
  arrange(N_seq) %>%
  rename(N = N_seq) %>%
  mutate(B = B_seq) 


## V = 500 #
V <- 500
N <- seq(0, V, by = 25)

N_seq <- N %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # a sequence of 0.5 to 1
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

# Creating the dataframe
TE_V500 <- data.frame(V, N_seq) %>%
  arrange(N_seq) %>%
  rename(N = N_seq) %>%
  mutate(B = B_seq) 


## V = 450 #
V <- 450
N <- seq(0, V, by = 25)

N_seq <- N %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # a sequence of 0.5 to 1
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

# Creating the dataframe
TE_V450 <- data.frame(V, N_seq) %>%
  arrange(N_seq) %>%
  rename(N = N_seq) %>%
  mutate(B = B_seq) 


## V = 400 #
V <- 400
N <- seq(0, V, by = 25)

N_seq <- N %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # a sequence of 0.5 to 1
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

# Creating the dataframe
TE_V400 <- data.frame(V, N_seq) %>%
  arrange(N_seq) %>%
  rename(N = N_seq) %>%
  mutate(B = B_seq) 


## V = 350 #
V <- 350
N <- seq(0, V, by = 25)

N_seq <- N %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # a sequence of 0.5 to 1
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

# Creating the dataframe
TE_V350 <- data.frame(V, N_seq) %>%
  arrange(N_seq) %>%
  rename(N = N_seq) %>%
  mutate(B = B_seq) 


## V = 300 #
V <- 300
N <- seq(0, V, by = 25)

N_seq <- N %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # a sequence of 0.5 to 1
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

# Creating the dataframe
TE_V300 <- data.frame(V, N_seq) %>%
  arrange(N_seq) %>%
  rename(N = N_seq) %>%
  mutate(B = B_seq) 


## V = 250 #
V <- 250
N <- seq(0, V, by = 25)

N_seq <- N %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # a sequence of 0.5 to 1
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

# Creating the dataframe
TE_V250 <- data.frame(V, N_seq) %>%
  arrange(N_seq) %>%
  rename(N = N_seq) %>%
  mutate(B = B_seq) 


## V = 200 #
V <- 200
N <- seq(0, V, by = 25)

N_seq <- N %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # a sequence of 0.5 to 1
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

# Creating the dataframe
TE_V200 <- data.frame(V, N_seq) %>%
  arrange(N_seq) %>%
  rename(N = N_seq) %>%
  mutate(B = B_seq) 


## V = 150 #
V <- 150
N <- seq(0, V, by = 25)

N_seq <- N %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # a sequence of 0.5 to 1
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

# Creating the dataframe
TE_V150 <- data.frame(V, N_seq) %>%
  arrange(N_seq) %>%
  rename(N = N_seq) %>%
  mutate(B = B_seq) 


## V = 100 #
V <- 100
N <- seq(0, V, by = 25)

N_seq <- N %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # a sequence of 0.5 to 1
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

# Creating the dataframe
TE_V100 <- data.frame(V, N_seq) %>%
  arrange(N_seq) %>%
  rename(N = N_seq) %>%
  mutate(B = B_seq) 


## V = 50 #
V <- 50
N <- seq(0, V, by = 25)

N_seq <- N %>% # Words produced in the dominant language
  rep(., length(B)) # generate N repetitions of the sequence based on length of B

B_seq <- B %>% # a sequence of 0.5 to 1
  rep(., length(N)) # generate N repetitions of the sequence based on length of N

# Creating the dataframe
TE_V50 <- data.frame(V, N_seq) %>%
  arrange(N_seq) %>%
  rename(N = N_seq) %>%
  mutate(B = B_seq) 


### Combining all dataframes and Calculate other variables
TE_fromVNB <- rbind(TE_V50, TE_V100, TE_V150, TE_V200, TE_V250, TE_V300, 
                    TE_V350, TE_V400, TE_V450, TE_V500, TE_V550, TE_V600) %>%
  # Create other variables
  mutate(W = N/(1-B), # Total word vocabulary of a child
         D = W-N, # Words produced in dominant language
         TE = (D*N)/V, # If D and N are independent, TE = DN/V
         C = W-TE, # Concept vocabulary (or total conceptual vocabulary size)
         Du = D-TE, # Unique words in dominant language
         Nu = N-TE) %>% # Unique words in non-dominant language
  # It is not possible for N > D, so keep only cases where D >= N
  filter(D >= N) %>%
  # In reality, it would be impossible to get negative numbers for any vocabulary variables, so filter out all cases with negative numbers
  filter(Nu >= 0) %>%
  # It is also not possible for D or N to exceed V, so filter out cases where D or N > V
  filter_at(vars(D, N), all_vars(. <= V)) %>%
  # Round to keep whole numbers only
  mutate_at(vars(-B), round, 0)

  ## filter out cases where D isn't whole number
  #filter(is.wholenumber(D)) %>%
  #filter_at(vars(TE, C, Du, Nu), any_vars(is.wholenumber(.))) %>%
  #filter(is.wholenumber(Nu)) 
```

#### Combine the 4 sets ####
```{r}
TE_computation <- TE_fromVWB %>%
  bind_rows(TE_fromVDN, TE_fromVDB, TE_fromVNB) %>%
  # Round to keep whole numbers only
  mutate_at(vars(-B), round, 0)

write.csv(TE_computation, 'TE_computation.csv')

  ## constrain all variables but B (balance) to be integers 
  #filter_at(vars(TE, C, Du, Nu), any_vars(is.wholenumber(.)))
```
